#!/bin/sh
case $1 in
    help)
        echo "$0 load <genesis_block_file>"
        exit 0
        ;;
    load)
        release_remote_ctl rpc "BlockchainNode.CLI.load_genesis(\"$2\")"
        ;;
esac
