#!/bin/sh

case $1 in
    add_gateway)
        release_remote_ctl rpc "BlockchainNode.CLI.add_gateway(\"$2\", \"$3\")"
        ;;
    assert_location)
        release_remote_ctl rpc "BlockchainNode.CLI.assert_location(\"$2\", \"$3\", \"$4\")"
        ;;
    assert_secure_location)
        release_remote_ctl rpc "BlockchainNode.CLI.assert_location(\"$2\", \"$3\", \"$4\", \"$5\")"
        ;;
esac
