#!/bin/sh

case $1 in
    add_gateway)
        release_remote_ctl rpc "BlockchainNode.Accounts.add_gateway('$2', '$3')"
        ;;
    assert_location)
        release_remote_ctl rpc "BlockchainNode.Gateways.assert_location('$2', '$3', '$4')"
        ;;
esac
