matrix:
  include:
  - os: linux
    env:
    - NODE_OS=linux
    language: elixir
    elixir: 1.7.3
    otp_release: 21.0.4
  - os: osx
    env:
    - KERL_CONFIGURE_OPTIONS="--disable-dynamic-ssl --with-ssl=/usr/local/Cellar/openssl/1.0.2m"
    - NODE_OS=darwin
    osx_image: xcode9.2
    language: minimal
    before_install:
    - brew install kerl
    - if [ ! -d $HOME/kerl/21.1 ]; then travis_wait 40 kerl build 21.1 21.1 && kerl install 21.1 $HOME/kerl/21.1; fi
    - . $HOME/kerl/21.1/activate
    - brew install elixir
    install: mix local.rebar --force; mix local.hex --force; mix deps.get

cache:
  directories:
    - $HOME/kerl
    - $HOME/Library/Caches/Homebrew
    - $HOME/build/helium/blockchain-node/deps

script: make deployable

after_success:
  - npm --prefix scripts install
  - npm run --prefix scripts release
