language: elixir
os:
  - osx
osx_image: xcode9.2
script: make deployable
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: "helium-wallet"
  region: us-west-2
  skip_cleanup: true
  upload-dir: node
  local_dir: latest
